# This file can be used to quickly set up the modmail bot

version: "3.7"

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "127.0.0.1:7777:5432"
    environment:
      POSTGRES_DB: modmail
      POSTGRES_PASSWORD: modmail
      POSTGRES_USER: modmail
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U modmail" ]
      interval: 2s
      timeout: 1s
      retries: 5

  modmail:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    tty: true
    volumes:
      - .:/modmail
    environment:
      database_uri: postgres://modmail:modmail@postgres:5432/modmail
