# Project Information
site_name: Discord Modmail
site_description: A Modmail bot for Discord. Allowing safe moderator conversations with server members one server at a time.
site_url: https://discord-modmail.readthedocs.io/

# Repository
repo_name: discord-modmail/modmail
repo_url: https://github.com/discord-modmail/modmail
edit_uri: "edit/main/docs/"

# Copyright
copyright: Copyright &copy; 2021 Discord Modmail

# Dev Configuration
dev_addr: 127.0.0.1:8008

# Configuration
theme:
  name: material
  locale: en

  # Colorscheme for the docs
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue
    accent: purple
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode

  # Enabled mkdocs features for the site
  features:
  - navigation.top
  - navigation.instant
  - search.suggest
  - search.highlight
  icon:
    repo: fontawesome/brands/github-alt
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: en

# Plugins
plugins:
- search
- markdownextradata:
    data: data

# Page tree
nav:
  - Home: README.md
  - Changelog: changelog.md
  - Security: security.md
  - Addons:
      - Overview: addons/README.md
      - Installation: addons/installation.md
      - Creating Plugins: addons/plugins.md
  - Contributing:
      - Guidelines: contributing.md
      - Creating an Extension: contributing/creating_an_extension.md



# Extensions
markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_div_format ''
- pymdownx.tabbed

# Customization
extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/discord-modmail/modmail
  - icon: fontawesome/brands/discord
    link: https://discord.gg/ERteGkedDW


# Custom css for the site
extra_css:
- css/termynal.css
- css/custom.css

# Custom javascript for the site
extra_javascript:
- https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
- js/termynal.js
- js/custom.js
