[types]
feature = { name = "Features" }
trivial = { name = "Trivial/Internal Changes" }
improvement = { name = "Improvements" }
bugfix = { name = "Bug Fixes" }
doc = { name = "Improved Documentation" }
deprecation = { name = "Deprecations" }
breaking = { name = "Breaking Changes" }
internal = { name = "Internal" }
