# Github Action Workflow that monitors dependency licenses

name: fossa

# Trigger the workflow on both pushes and pull requests
# that edit dependency files
on:
  push:
    paths:
      - pyproject.toml
      - poetry.lock
      - requirements.txt
  pull_request:
    paths:
      - pyproject.toml
      - poetry.lock
      - requirements.txt

# Brand new concurrency setting! This ensures that not more than one run can be triggered for the same commit.
# It is useful for pull requests coming from the main repository since both triggers will match.
concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      uses: fossas/fossa-action@v1
      with:
        api-key: ${{ secrets.FOSSA_API_KEY }}
