name: Check for a news entry

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, reopened]

jobs:
  check-news:
    runs-on: ubuntu-latest

    steps:
      # Checks out the repository in the current folder.
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up the right version of Python
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install the required dependencies for using the feature, we aren't using cache here
      # as the number is relatively small and having cache would be complete redundancy.
      - name: Install dependencies using pip
        run: |
          pip install tomli requests

      # Run the script for checking if there is a news entry for the current PR
      - name: Check for a news entry in the news/next
        run: |
          python -m scripts.news.check_news_workflow ${{ github.event.pull_request.number }}
